INSERT INTO product_category VALUES (NULL,'3D Printers');
INSERT INTO product_category VALUES (NULL,'Adhesives, Coatings & Sealants');
INSERT INTO product_category VALUES (NULL,'Advertising & Marketing');
INSERT INTO product_category VALUES (NULL,'Agriculture');
INSERT INTO product_category VALUES (NULL,'Air Sports');
INSERT INTO product_category VALUES (NULL,'Arcade Equipment');
INSERT INTO product_category VALUES (NULL,'Audio');
INSERT INTO product_category VALUES (NULL,'Baby & Toddler Furniture');
INSERT INTO product_category VALUES (NULL,'Baby & Toddler Gift Sets');
INSERT INTO product_category VALUES (NULL,'Baby Bathing');
INSERT INTO product_category VALUES (NULL,'Baby Health');
INSERT INTO product_category VALUES (NULL,'Baby Safety');
INSERT INTO product_category VALUES (NULL,'Baby Toys');
INSERT INTO product_category VALUES (NULL,'Baby Transport');
INSERT INTO product_category VALUES (NULL,'Baby Transport Accessories');
INSERT INTO product_category VALUES (NULL,'Backpack Accessories');
INSERT INTO product_category VALUES (NULL,'Backpacks');
INSERT INTO product_category VALUES (NULL,'Bathroom Accessories');
INSERT INTO product_category VALUES (NULL,'Beds & Accessories');
INSERT INTO product_category VALUES (NULL,'Benches');
INSERT INTO product_category VALUES (NULL,'Beverages');
INSERT INTO product_category VALUES (NULL,'Book Accessories');
INSERT INTO product_category VALUES (NULL,'Books');
INSERT INTO product_category VALUES (NULL,'Building Materials');
INSERT INTO product_category VALUES (NULL,'Business Bags');
INSERT INTO product_category VALUES (NULL,'Cabinetry');
INSERT INTO product_category VALUES (NULL,'Cabinets & Storage');
INSERT INTO product_category VALUES (NULL,'Camera & Optic Accessories');
INSERT INTO product_category VALUES (NULL,'Cameras');
INSERT INTO product_category VALUES (NULL,'Carts & Islands');
INSERT INTO product_category VALUES (NULL,'Chair Accessories');
INSERT INTO product_category VALUES (NULL,'Chairs');
INSERT INTO product_category VALUES (NULL,'Chemicals');
INSERT INTO product_category VALUES (NULL,'Circuit Components');
INSERT INTO product_category VALUES (NULL,'Clothing');
INSERT INTO product_category VALUES (NULL,'Clothing Accessories');
INSERT INTO product_category VALUES (NULL,'Combat Sports');
INSERT INTO product_category VALUES (NULL,'Communications');
INSERT INTO product_category VALUES (NULL,'Components');
INSERT INTO product_category VALUES (NULL,'Computer Software');
INSERT INTO product_category VALUES (NULL,'Computers');
INSERT INTO product_category VALUES (NULL,'Construction');
INSERT INTO product_category VALUES (NULL,'Cosmetic & Toiletry Bags');
INSERT INTO product_category VALUES (NULL,'Costumes & Accessories');
INSERT INTO product_category VALUES (NULL,'Dancing');
INSERT INTO product_category VALUES (NULL,'Decor');
INSERT INTO product_category VALUES (NULL,'Dentistry');
INSERT INTO product_category VALUES (NULL,'Diaper Bags');
INSERT INTO product_category VALUES (NULL,'Diapering');
INSERT INTO product_category VALUES (NULL,'Digital Goods & Currency');
INSERT INTO product_category VALUES (NULL,'Duffel Bags');
INSERT INTO product_category VALUES (NULL,'DVDs & Videos');
INSERT INTO product_category VALUES (NULL,'Electrical Motors');
INSERT INTO product_category VALUES (NULL,'Electrical Supplies');
INSERT INTO product_category VALUES (NULL,'Electronics Accessories');
INSERT INTO product_category VALUES (NULL,'Emergency Preparedness');
INSERT INTO product_category VALUES (NULL,'Entertainment Centers & TV Stands');
INSERT INTO product_category VALUES (NULL,'Erotic');
INSERT INTO product_category VALUES (NULL,'Exercise & Fitness');
INSERT INTO product_category VALUES (NULL,'Fanny Packs');
INSERT INTO product_category VALUES (NULL,'Filing & Organization');
INSERT INTO product_category VALUES (NULL,'Film & Television');
INSERT INTO product_category VALUES (NULL,'Finance & Insurance');
INSERT INTO product_category VALUES (NULL,'Fire & Gas Safety');
INSERT INTO product_category VALUES (NULL,'Fireplace & Wood Stove Accessories');
INSERT INTO product_category VALUES (NULL,'Fireplaces');
INSERT INTO product_category VALUES (NULL,'Food Items');
INSERT INTO product_category VALUES (NULL,'Food Service');
INSERT INTO product_category VALUES (NULL,'Forestry & Logging');
INSERT INTO product_category VALUES (NULL,'Furniture Sets');
INSERT INTO product_category VALUES (NULL,'Futon Frames');
INSERT INTO product_category VALUES (NULL,'Futon Pads');
INSERT INTO product_category VALUES (NULL,'Futons');
INSERT INTO product_category VALUES (NULL,'Game Timers');
INSERT INTO product_category VALUES (NULL,'Games');
INSERT INTO product_category VALUES (NULL,'General Supplies');
INSERT INTO product_category VALUES (NULL,'Generators');
INSERT INTO product_category VALUES (NULL,'GPS');
INSERT INTO product_category VALUES (NULL,'GPS Accessories');
INSERT INTO product_category VALUES (NULL,'GPS Trackers');
INSERT INTO product_category VALUES (NULL,'Gymnastics');
INSERT INTO product_category VALUES (NULL,'Hairdressing & Cosmetology');
INSERT INTO product_category VALUES (NULL,'Handbag & Wallet Accessories');
INSERT INTO product_category VALUES (NULL,'Handbags, Wallets & Cases');
INSERT INTO product_category VALUES (NULL,'Hardware Accessories');
INSERT INTO product_category VALUES (NULL,'Hardware Torches');
INSERT INTO product_category VALUES (NULL,'Health Care');
INSERT INTO product_category VALUES (NULL,'Heavy Machinery');
INSERT INTO product_category VALUES (NULL,'Hobbies & Creative Arts');
INSERT INTO product_category VALUES (NULL,'Home Fencing');
INSERT INTO product_category VALUES (NULL,'Home Security');
INSERT INTO product_category VALUES (NULL,'Hotel & Hospitality');
INSERT INTO product_category VALUES (NULL,'Household Appliance Accessories');
INSERT INTO product_category VALUES (NULL,'Household Appliances');
INSERT INTO product_category VALUES (NULL,'Household Supplies');
INSERT INTO product_category VALUES (NULL,'Impulse Sealers');
INSERT INTO product_category VALUES (NULL,'Indoor Games');
INSERT INTO product_category VALUES (NULL,'Industrial Storage');
INSERT INTO product_category VALUES (NULL,'Industrial Storage Accessories');
INSERT INTO product_category VALUES (NULL,'Insulation');
INSERT INTO product_category VALUES (NULL,'Jewelry');
INSERT INTO product_category VALUES (NULL,'Jewelry Cleaning & Care');
INSERT INTO product_category VALUES (NULL,'Jumping');
INSERT INTO product_category VALUES (NULL,'Key Blanks');
INSERT INTO product_category VALUES (NULL,'Kitchen & Dining');
INSERT INTO product_category VALUES (NULL,'Law Enforcement');
INSERT INTO product_category VALUES (NULL,'Lawn & Garden');
INSERT INTO product_category VALUES (NULL,'Lighting');
INSERT INTO product_category VALUES (NULL,'Lighting Accessories');
INSERT INTO product_category VALUES (NULL,'Linens & Bedding');
INSERT INTO product_category VALUES (NULL,'Live Animals');
INSERT INTO product_category VALUES (NULL,'Locks & Locksmithing');
INSERT INTO product_category VALUES (NULL,'Luggage Accessories');
INSERT INTO product_category VALUES (NULL,'Magazines & Newspapers');
INSERT INTO product_category VALUES (NULL,'Manufacturing');
INSERT INTO product_category VALUES (NULL,'Marine Electronics');
INSERT INTO product_category VALUES (NULL,'Material Handling');
INSERT INTO product_category VALUES (NULL,'Medical');
INSERT INTO product_category VALUES (NULL,'Memorial Ceremony Supplies');
INSERT INTO product_category VALUES (NULL,'Messenger Bags');
INSERT INTO product_category VALUES (NULL,'Mining & Quarrying');
INSERT INTO product_category VALUES (NULL,'Music');
INSERT INTO product_category VALUES (NULL,'Name Plates');
INSERT INTO product_category VALUES (NULL,'Networking');
INSERT INTO product_category VALUES (NULL,'Nursing & Feeding');
INSERT INTO product_category VALUES (NULL,'Office & Chair Mats');
INSERT INTO product_category VALUES (NULL,'Office Carts');
INSERT INTO product_category VALUES (NULL,'Office Equipment');
INSERT INTO product_category VALUES (NULL,'Office Furniture');
INSERT INTO product_category VALUES (NULL,'Office Instruments');
INSERT INTO product_category VALUES (NULL,'Optics');
INSERT INTO product_category VALUES (NULL,'Ottomans');
INSERT INTO product_category VALUES (NULL,'Outdoor Furniture');
INSERT INTO product_category VALUES (NULL,'Outdoor Furniture Accessories');
INSERT INTO product_category VALUES (NULL,'Outdoor Play Equipment');
INSERT INTO product_category VALUES (NULL,'Outdoor Recreation');
INSERT INTO product_category VALUES (NULL,'Painting & Wall Covering Supplies');
INSERT INTO product_category VALUES (NULL,'Paper Handling');
INSERT INTO product_category VALUES (NULL,'Parasols & Rain Umbrellas');
INSERT INTO product_category VALUES (NULL,'Party & Celebration');
INSERT INTO product_category VALUES (NULL,'Personal Care');
INSERT INTO product_category VALUES (NULL,'Pet Supplies');
INSERT INTO product_category VALUES (NULL,'Photography');
INSERT INTO product_category VALUES (NULL,'Piercing & Tattooing');
INSERT INTO product_category VALUES (NULL,'Plants');
INSERT INTO product_category VALUES (NULL,'Plug & Play TV Games');
INSERT INTO product_category VALUES (NULL,'Plumbing');
INSERT INTO product_category VALUES (NULL,'Pool & Spa');
INSERT INTO product_category VALUES (NULL,'Potty Training');
INSERT INTO product_category VALUES (NULL,'Presentation Supplies');
INSERT INTO product_category VALUES (NULL,'Print, Copy, Scan & Fax');
INSERT INTO product_category VALUES (NULL,'Print, Copy, Scan & Fax Accessories');
INSERT INTO product_category VALUES (NULL,'Product Manuals');
INSERT INTO product_category VALUES (NULL,'Puzzles');
INSERT INTO product_category VALUES (NULL,'Racquet Sports');
INSERT INTO product_category VALUES (NULL,'Religious Items');
INSERT INTO product_category VALUES (NULL,'Renewable Energy');
INSERT INTO product_category VALUES (NULL,'Retail');
INSERT INTO product_category VALUES (NULL,'Roofing');
INSERT INTO product_category VALUES (NULL,'Room Divider Accessories');
INSERT INTO product_category VALUES (NULL,'Room Dividers');
INSERT INTO product_category VALUES (NULL,'Science & Laboratory');
INSERT INTO product_category VALUES (NULL,'Sheet Music');
INSERT INTO product_category VALUES (NULL,'Shelving');
INSERT INTO product_category VALUES (NULL,'Shelving Accessories');
INSERT INTO product_category VALUES (NULL,'Shipping Supplies');
INSERT INTO product_category VALUES (NULL,'Shoe Accessories');
INSERT INTO product_category VALUES (NULL,'Shoes');
INSERT INTO product_category VALUES (NULL,'Shop Stools');
INSERT INTO product_category VALUES (NULL,'Shopping Totes');
INSERT INTO product_category VALUES (NULL,'Signage');
INSERT INTO product_category VALUES (NULL,'Smoking Accessories');
INSERT INTO product_category VALUES (NULL,'Sofa Accessories');
INSERT INTO product_category VALUES (NULL,'Sofas');
INSERT INTO product_category VALUES (NULL,'Storage Tanks');
INSERT INTO product_category VALUES (NULL,'Suitcases');
INSERT INTO product_category VALUES (NULL,'Swaddling Blankets');
INSERT INTO product_category VALUES (NULL,'Table Accessories');
INSERT INTO product_category VALUES (NULL,'Tables');
INSERT INTO product_category VALUES (NULL,'Team Sports');
INSERT INTO product_category VALUES (NULL,'Tobacco Products');
INSERT INTO product_category VALUES (NULL,'Toll Collection Devices');
INSERT INTO product_category VALUES (NULL,'Tool Accessories');
INSERT INTO product_category VALUES (NULL,'Tools');
INSERT INTO product_category VALUES (NULL,'Toys');
INSERT INTO product_category VALUES (NULL,'Train Cases');
INSERT INTO product_category VALUES (NULL,'Umbrella Sleeves & Cases');
INSERT INTO product_category VALUES (NULL,'Vehicle Parts & Accessories');
INSERT INTO product_category VALUES (NULL,'Video');
INSERT INTO product_category VALUES (NULL,'Video Game Console Accessories');
INSERT INTO product_category VALUES (NULL,'Video Game Consoles');
INSERT INTO product_category VALUES (NULL,'Video Game Software');
INSERT INTO product_category VALUES (NULL,'Water Sports');
INSERT INTO product_category VALUES (NULL,'Weapons');
INSERT INTO product_category VALUES (NULL,'Wedding Ceremony Supplies');
INSERT INTO product_category VALUES (NULL,'Winter Sports');
INSERT INTO product_category VALUES (NULL,'Wood Stoves');
INSERT INTO product_category VALUES (NULL,'Work Safety Protective Gear');